site_name: Simha & Sarwa Associates 
site_url: https://akhildp.github.io/simha-sarva/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.top
    - toc.integrate: false
  language: en
  features:
    - navigation.tabs
    - navigation.top
  font:
    text: Inter
    code: Inter
  favicon: images/favicon.svg

extra:
  generator: false
  
nav:
  - Home: index.md
  - Firm Philosophy: philosophy.md
  - People: people.md
  - Practice Areas: practice-areas.md
  - About the Firm: about.md
  - Blog and updates: blog.md
  - Contact: contact.md

extra_javascript:
  - js/skip-link.js
  - js/disclaimer-popup.js
  - js/people-toggle.js
  - js/footer-and-backtotop.js

extra_css:
  - css/custom.css
  - css/disclaimer.css

markdown_extensions:
  - md_in_html