site_name: Simha & Sarwa Associates 
site_url: https://akhildp.github.io/simha-sarva/
use_directory_urls: false

theme:
  name: material
  features:
    - navigation.top
    - toc.integrate: false
  language: en
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
  font:
    text: Inter
    code: Inter

extra:
  generator: false
  
nav:
  - Home: index.md
  - About the Firm: about.md
  - Practice Areas: practice-areas.md
  - People: people.md
  - Contact: contact.md

extra_javascript:
  - js/disclaimer-popup.js
  - js/people-toggle.js

extra_css:
  - css/custom.css
  - css/disclaimer.css

markdown_extensions:
  - md_in_html